<?php declare(strict_types=1);

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function whiskeydex_theme($existing, $type, $theme, $path): array {
  $stop = null;
  return [
    'collection' => [
      'render element' => 'elements',
    ],
    'collection_item' => [
      'render element' => 'elements',
    ],
    'distillery' => [
      'render element' => 'elements',
    ],
    'whiskey' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function whiskeydex_preprocess_collection(&$variables) {
  $variables += ['content' => []];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

}
