name: Main
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

env:
  # shivammathur/setup-php
  PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
  PHP_VERSION: 8.1
  REGISTRY: registry.digitalocean.com/whiskeydex
  REPOSITORY: whiskeydex
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: PHPCS
        run: php vendor/bin/phpcs
      - name: PHPStan
        run: php vendor/bin/phpstan analyze

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - run: php vendor/bin/drush app:env:generate --sqlite
      # - run: yarn install --non-interactive --cwd $GITHUB_WORKSPACE/web/core

      - run: mkdir -p private/browsertest_output

      - run: "cd web && php -S 127.0.0.1:8080 .ht.router.php &"
      # Chromedriver already exists
      - run: "chromedriver &"

      - name: phpunit
        run: php vendor/bin/phpunit web/modules/custom

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Install dependencies
        run: npm ci

      - run: php vendor/bin/drush app:env:generate --sqlite
      - run: php vendor/bin/drush site:install --yes

      - run: "cd web && php -S 127.0.0.1:8080 .ht.router.php &"

      - name: cypress
        run: npx cypress run

      - uses: actions/upload-artifact@v3
        if: ${{ failure() || success() }}
        with:
          name: nightwatch_reports
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7


  # build:
  #   needs:
  #     - lint
  #     - test
  #   runs-on: ubuntu-latest
  #   env:
  #     DOCKER_BUILDKIT: 1
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: docker login
  #       run: docker login registry.digitalocean.com --username ${{ secrets.DO_REGISTRY_TOKEN }} --password ${{ secrets.DO_REGISTRY_TOKEN }}

  #     - name: Build image
  #       run: |
  #         docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
  #     - name: Push image
  #       if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
  #       run: |
  #         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  # deploy:
  #   needs:
  #     - build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: DigitalOcean App Platform deployment
  #       if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
  #       uses: digitalocean/app_action@v1.1.0
  #       with:
  #         app_name: whiskeydex
  #         token: ${{ secrets.DO_REGISTRY_TOKEN }}
  #         images: '[{
  #                     "name": "app",
  #                     "image":{
  #                       "registry_type": "DOCR",
  #                       "repository": "whiskeydex",
  #                       "tag": "${{ github.sha }}"
  #                     }
  #                   },
  #                   {
  #                     "name": "worker",
  #                     "image":{
  #                       "registry_type": "DOCR",
  #                       "repository": "whiskeydex",
  #                       "tag": "${{ github.sha }}"
  #                     }
  #                   }]'
