name: Main
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

env:
  # shivammathur/setup-php
  PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
  PHP_VERSION: 8.1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: PHPCS
        run: php vendor/bin/phpcs
      - name: PHPStan
        run: php vendor/bin/phpstan analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - run: php vendor/bin/drush app:env:generate --sqlite
      - run: yarn install --non-interactive --cwd $GITHUB_WORKSPACE/web/core

      - run: mkdir -p private/browsertest_output

      - run: "cd web && php -S 127.0.0.1:8080 .ht.router.php &"
      # Chromedriver already exists
      - run: "chromedriver &"

      - name: phpunit
        run: php vendor/bin/phpunit web/modules/custom

#      - name: nightwatch
#        run: |
#          cd web/core
#          yarn test:nightwatch --tag whiskeydex
#        env:
#          DRUPAL_TEST_BASE_URL: http://127.0.0.1:8080
#          DRUPAL_TEST_DB_URL: sqlite://localhost/sites/default/files/.ht.sqlite
#          DRUPAL_TEST_WEBDRIVER_HOSTNAME: 127.0.0.1
#          DRUPAL_TEST_WEBDRIVER_PORT: 9515
#          DRUPAL_TEST_CHROMEDRIVER_AUTOSTART: 'false'
#          DRUPAL_TEST_WEBDRIVER_CHROME_ARGS: "--disable-gpu --headless --no-sandbox"
#          DRUPAL_NIGHTWATCH_OUTPUT: reports/nightwatch
#          DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES: node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest
#          DRUPAL_NIGHTWATCH_SEARCH_DIRECTORY: ../

  build:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: whiskeydex
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Push image
        #if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: whiskeydex
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
